import { Note, notesTable } from '@/models/note.model';
import { PGlite } from '@electric-sql/pglite';
import { datasource, ValueOrPromise } from '@venizia/ignis';
import { BasePostgresDataSource } from '@venizia/ignis/postgres';
import { PGliteDriver } from '@venizia/ignis/postgres/pglite';
import { drizzle } from 'drizzle-orm/pglite';
import { migrate } from 'drizzle-orm/pglite/migrator';
import { mkdirSync } from 'node:fs';
import { dirname } from 'node:path';

interface IDataSourceConfigs {
  /**
   * A directory PGlite owns, or `undefined` for an in-memory database that dies with the process.
   */
  dataDir?: string;
}

/** Runtime state lives under `app_data/`, which is gitignored repository-wide. */
const DEFAULT_DATA_DIR = './app_data/database/pgdata';

/** Keyed by `TABLE_NAME`, which is what Drizzle's relational query API resolves against. */
type TNoteDataSourceSchema = { [Note.TABLE_NAME]: typeof notesTable };

/** Generated by `bun run migrate:generate` from the model - never hand-edited. */
const MIGRATIONS_FOLDER = './migration';

/**
 * The fourth type parameter is the raw client `getClient()`
 * hands back - `pg.Pool` by default, `PGlite` here.
 */
@datasource({ driver: PGliteDriver })
export class PGliteDataSource extends BasePostgresDataSource<
  IDataSourceConfigs,
  TNoteDataSourceSchema,
  {},
  PGlite
> {
  constructor() {
    super({
      name: PGliteDataSource.name,
      config: { dataDir: process.env.APP_ENV_PGLITE_DATA_DIR ?? DEFAULT_DATA_DIR },
      schema: { [Note.TABLE_NAME]: notesTable },
    });
  }

  override async configure(): Promise<void> {
    // PGlite creates its own data directory but not the folders above it, so a missing `app_data`
    // is an ENOENT at boot rather than a fresh database.
    if (this.settings.dataDir) {
      mkdirSync(dirname(this.settings.dataDir), { recursive: true });
    }

    const client = new PGlite(this.settings.dataDir);
    await client.waitReady;

    // Applied in-process rather than by the CLI: PGlite holds an exclusive lock on its data
    // directory, so `drizzle-kit migrate` cannot run against a database the app already opened.
    // `migrate()` records what it ran in `drizzle.__drizzle_migrations`, so later boots are no-ops.
    await migrate(drizzle({ client }), { migrationsFolder: MIGRATIONS_FOLDER });

    this.client = client;
  }

  /**
   * PGlite has no URL. Only application code calls
   * this, so the data directory is the honest answer.
   */
  override getConnectionString(): ValueOrPromise<string> {
    return this.settings.dataDir ?? ':memory:';
  }
}
