import { dirname, relative, sep } from 'node:path';
import { ArtifactStereotypes } from './common/constants';
import type { IScannedArtifact } from './common/types';

/** Renders the generated index: deterministic text, plain static imports, no IGNIS import - the object is type-checked where `registerArtifacts` receives it. */
export class ArtifactIndexEmitter {
  static readonly HEADER =
    '// AUTO-GENERATED by @venizia/ignis-boot - do not edit. Regenerate: ignis-artifacts generate --root src --out src/generated/artifacts.ts';

  static render(opts: {
    artifacts: IScannedArtifact[];
    outFile: string;
    exportName: string;
  }): string {
    const { artifacts, outFile, exportName } = opts;
    const emitted = artifacts.filter(artifact => artifact.type !== 'model');

    const imports = emitted
      .map(artifact => ({
        name: artifact.className,
        path: ArtifactIndexEmitter.importPath({ from: outFile, to: artifact.filePath }),
      }))
      .sort((a, b) => a.path.localeCompare(b.path) || a.name.localeCompare(b.name))
      .map(entry => `import { ${entry.name} } from '${entry.path}';`);

    const fields = ArtifactStereotypes.EMIT_ORDER.map(({ type, field }) => {
      const names = emitted
        .filter(artifact => artifact.type === type)
        .map(artifact => artifact.className)
        .sort((a, b) => a.localeCompare(b));

      return `  ${field}: [${names.join(', ')}],`;
    });

    return [
      ArtifactIndexEmitter.HEADER,
      ...imports,
      '',
      `export const ${exportName} = {`,
      ...fields,
      '};',
      '',
    ].join('\n');
  }

  private static importPath(opts: { from: string; to: string }): string {
    const raw = relative(dirname(opts.from), opts.to).split(sep).join('/').replace(/\.ts$/, '');
    return raw.startsWith('.') ? raw : `./${raw}`;
  }
}
