import { dirname, relative, sep } from 'node:path';
import { ArtifactStereotypes, ArtifactTypes, type IScannedArtifact } from './common';

/** Renders the generated index: deterministic text, plain static imports, no IGNIS import - the object is type-checked where `registerArtifacts` receives it. */
export class ArtifactIndexEmitter {
  /** Mirrors `printWidth` in @venizia/dev-configs prettier settings. */
  static readonly PRINT_WIDTH = 100;

  static readonly HEADER =
    '// AUTO-GENERATED by @venizia/ignis-boot - do not edit. Regenerate: ignis-artifacts generate --root src --out src/generated/artifacts.ts';

  static render(opts: {
    artifacts: IScannedArtifact[];
    outFile: string;
    exportName: string;
  }): string {
    const { artifacts, outFile, exportName } = opts;
    const emitted = artifacts.filter(artifact => artifact.type !== ArtifactTypes.MODEL);

    const imports = emitted
      .map(artifact => ({
        name: artifact.className,
        path: ArtifactIndexEmitter.importPath({ from: outFile, to: artifact.filePath }),
      }))
      .sort((a, b) => a.path.localeCompare(b.path) || a.name.localeCompare(b.name))
      .map(entry => `import { ${entry.name} } from '${entry.path}';`);

    const fields = ArtifactStereotypes.EMIT_ORDER.flatMap(({ type, field }) => {
      const names = emitted
        .filter(artifact => artifact.type === type)
        .map(artifact => artifact.className)
        .sort((a, b) => a.localeCompare(b));

      return ArtifactIndexEmitter.renderField({ field, names });
    });

    return [
      ArtifactIndexEmitter.HEADER,
      ...imports,
      '',
      `export const ${exportName} = {`,
      ...fields,
      '};',
      '',
    ].join('\n');
  }

  /** One line while it fits the repo's prettier width, else one name per line - so `prettier -l` on the generated file stays quiet. */
  private static renderField(opts: { field: string; names: string[] }): string[] {
    const { field, names } = opts;
    const singleLine = `  ${field}: [${names.join(', ')}],`;

    if (singleLine.length <= ArtifactIndexEmitter.PRINT_WIDTH) {
      return [singleLine];
    }

    return [`  ${field}: [`, ...names.map(name => `    ${name},`), '  ],'];
  }

  private static importPath(opts: { from: string; to: string }): string {
    const raw = relative(dirname(opts.from), opts.to).split(sep).join('/').replace(/\.ts$/, '');
    return raw.startsWith('.') ? raw : `./${raw}`;
  }
}
