import type { TBuildInfoRecord } from '@venizia/ignis-helpers/core';
import { BuildInfoFormats, type TBuildInfoFormat } from './common';

/** Renders the stamp: a static `ts` const a bundler bakes in, or the same record as `json` for a Vite app or a Tauri shell. */
export class BuildInfoEmitter {
  static readonly DEFAULT_EXPORT_NAME = 'BUILD_INFO';

  static render(opts: {
    buildInfo: TBuildInfoRecord;
    format: TBuildInfoFormat;
    exportName: string;
  }): string {
    const { buildInfo, format, exportName } = opts;

    if (format === BuildInfoFormats.JSON) {
      return `${JSON.stringify(buildInfo, null, 2)}\n`;
    }

    const fields = Object.entries(buildInfo)
      .map(([key, value]) => `  ${key}: ${JSON.stringify(value)},`)
      .join('\n');

    return [
      '// AUTO-GENERATED by @venizia/ignis-boot - do not edit. Regenerate: ignis-build-info generate',
      `export const ${exportName} = {`,
      fields,
      '} as const;',
      '',
    ].join('\n');
  }
}
