import { ArticleDocument } from '@/models/entities';
import { ArticleRepository } from '@/repositories';
import { BindingKeys, BindingNamespaces, controller, inject } from '@venizia/ignis';
import { SearchControllerFactory } from '@venizia/ignis/typesense/controllers';

const BASE_PATH = '/articles';

/**
 * ArticleSearchController - the full-text/vector/hybrid/raw search verbs the CRUD factory cannot
 * generate: turnkey `POST /articles/search` (single-collection, dispatched through
 * ArticleRepository.search()) and `POST /articles/multi-search` (cross-collection, dispatched
 * through ArticleRepository.dataSource.multiSearch()) - generated by SearchControllerFactory,
 * mirroring how ControllerFactory.defineCrudController generates ArticleController.
 */
const _SearchController = SearchControllerFactory.defineSearchController({
  entity: ArticleDocument,
  repository: { name: ArticleRepository.name },
  controller: {
    name: 'ArticleSearchController',
    basePath: BASE_PATH,
  },
});

@controller({ path: BASE_PATH })
export class ArticleSearchController extends _SearchController {
  constructor(
    @inject({
      key: BindingKeys.build({
        namespace: BindingNamespaces.REPOSITORY,
        key: ArticleRepository.name,
      }),
    })
    repository: ArticleRepository,
  ) {
    super(repository);
  }
}
