/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/configurations/count": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Count records matching where condition */
        get: {
            parameters: {
                query: {
                    /** @description Query conditions for selecting data. */
                    where: Record<string, never>;
                };
                header?: {
                    /** @description Optional request ID */
                    "x-request-id"?: string;
                    /** @description Optional request channel */
                    "x-request-channel"?: string;
                    /** @description Optional request device info */
                    "x-device-info"?: string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Total count of matching records */
                200: {
                    headers: {
                        /** @description Echo of the request tracing ID */
                        "x-request-id"?: string;
                        /** @description Number of records in response */
                        "x-response-count"?: string;
                        /** @description Response format indicator */
                        "x-response-format"?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @default 0 */
                            count: number;
                        };
                    };
                };
                /** @description Error Response */
                "4XX": {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Error Response */
                "5XX": {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/configurations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Find records with filter, pagination, sorting, and relations */
        get: {
            parameters: {
                query?: {
                    /** @description A comprehensive filter object for querying data, including conditions, field selection, relations, pagination, and sorting. */
                    filter?: Record<string, never>;
                };
                header?: {
                    /** @description Optional request ID */
                    "x-request-id"?: string;
                    /** @description Optional request channel */
                    "x-request-channel"?: string;
                    /** @description Optional request device info */
                    "x-device-info"?: string;
                    /** @description Controls response format. When "true" (default): returns {count, data}. When "false": returns data only. */
                    "x-request-count"?: string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Array of matching records (with optional count) */
                200: {
                    headers: {
                        /** @description Echo of the request tracing ID */
                        "x-request-id"?: string;
                        /** @description Number of records in response */
                        "x-response-count"?: string;
                        /** @description Response format indicator */
                        "x-response-format"?: string;
                        /** @description Content range for pagination (e.g., "records 0-24/100") */
                        "content-range"?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @default 0 */
                            count: number;
                            data: {
                                id: string;
                                createdBy: string | null;
                                modifiedBy: string | null;
                                code: string;
                                group: string;
                                description: string | null;
                            }[];
                        } | {
                            id: string;
                            createdBy: string | null;
                            modifiedBy: string | null;
                            code: string;
                            group: string;
                            description: string | null;
                        }[];
                    };
                };
                /** @description Error Response */
                "4XX": {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Error Response */
                "5XX": {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        /** @description Create new record */
        post: {
            parameters: {
                query?: never;
                header?: {
                    /** @description Optional request ID */
                    "x-request-id"?: string;
                    /** @description Optional request channel */
                    "x-request-channel"?: string;
                    /** @description Optional request device info */
                    "x-device-info"?: string;
                    /** @description Controls response format. When "true" (default): returns {count, data}. When "false": returns data only. */
                    "x-request-count"?: string;
                };
                path?: never;
                cookie?: never;
            };
            /** @description Record data (required fields must be provided) */
            requestBody?: {
                content: {
                    "application/json": {
                        id?: string;
                        code: string;
                        group: string;
                        description?: string | null;
                    };
                };
            };
            responses: {
                /** @description Created record with generated fields (id, createdAt, etc.) */
                200: {
                    headers: {
                        /** @description Echo of the request tracing ID */
                        "x-request-id"?: string;
                        /** @description Number of records in response */
                        "x-response-count"?: string;
                        /** @description Response format indicator */
                        "x-response-format"?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @default 0 */
                            count: number;
                            data: {
                                id: string;
                                createdBy: string | null;
                                modifiedBy: string | null;
                                code: string;
                                group: string;
                                description: string | null;
                            };
                        } | {
                            id: string;
                            createdBy: string | null;
                            modifiedBy: string | null;
                            code: string;
                            group: string;
                            description: string | null;
                        };
                    };
                };
                /** @description Error Response */
                "4XX": {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Error Response */
                "5XX": {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        /** @description Bulk delete records matching where condition (irreversible) */
        delete: {
            parameters: {
                query?: {
                    /** @description Query conditions for selecting data. */
                    where?: Record<string, never>;
                };
                header?: {
                    /** @description Optional request ID */
                    "x-request-id"?: string;
                    /** @description Optional request channel */
                    "x-request-channel"?: string;
                    /** @description Optional request device info */
                    "x-device-info"?: string;
                    /** @description Controls response format. When "true" (default): returns {count, data}. When "false": returns data only. */
                    "x-request-count"?: string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Array of deleted records */
                200: {
                    headers: {
                        /** @description Echo of the request tracing ID */
                        "x-request-id"?: string;
                        /** @description Number of records in response */
                        "x-response-count"?: string;
                        /** @description Response format indicator */
                        "x-response-format"?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @default 0 */
                            count: number;
                            data: {
                                id: string;
                                createdBy: string | null;
                                modifiedBy: string | null;
                                code: string;
                                group: string;
                                description: string | null;
                            }[];
                        } | {
                            id: string;
                            createdBy: string | null;
                            modifiedBy: string | null;
                            code: string;
                            group: string;
                            description: string | null;
                        }[];
                    };
                };
                /** @description Error Response */
                "4XX": {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Error Response */
                "5XX": {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        /** @description Bulk update records matching where condition */
        patch: {
            parameters: {
                query?: {
                    /** @description Query conditions for selecting data. */
                    where?: Record<string, never>;
                };
                header?: {
                    /** @description Optional request ID */
                    "x-request-id"?: string;
                    /** @description Optional request channel */
                    "x-request-channel"?: string;
                    /** @description Optional request device info */
                    "x-device-info"?: string;
                    /** @description Controls response format. When "true" (default): returns {count, data}. When "false": returns data only. */
                    "x-request-count"?: string;
                };
                path?: never;
                cookie?: never;
            };
            /** @description Partial data to apply to all matches */
            requestBody?: {
                content: {
                    "application/json": {
                        code?: string;
                        group?: string;
                        description?: string | null;
                        /** @description Query conditions for selecting data. */
                        where?: Record<string, never>;
                    };
                };
            };
            responses: {
                /** @description Array of updated records */
                200: {
                    headers: {
                        /** @description Echo of the request tracing ID */
                        "x-request-id"?: string;
                        /** @description Number of records in response */
                        "x-response-count"?: string;
                        /** @description Response format indicator */
                        "x-response-format"?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @default 0 */
                            count: number;
                            data: {
                                id: string;
                                createdBy: string | null;
                                modifiedBy: string | null;
                                code: string;
                                group: string;
                                description: string | null;
                            }[];
                        } | {
                            id: string;
                            createdBy: string | null;
                            modifiedBy: string | null;
                            code: string;
                            group: string;
                            description: string | null;
                        }[];
                    };
                };
                /** @description Error Response */
                "4XX": {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Error Response */
                "5XX": {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/configurations/find-one": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Find first record matching filter */
        get: {
            parameters: {
                query?: {
                    /** @description A comprehensive filter object for querying data, including conditions, field selection, relations, pagination, and sorting. */
                    filter?: Record<string, never>;
                };
                header?: {
                    /** @description Optional request ID */
                    "x-request-id"?: string;
                    /** @description Optional request channel */
                    "x-request-channel"?: string;
                    /** @description Optional request device info */
                    "x-device-info"?: string;
                    /** @description Controls response format. When "true" (default): returns {count, data}. When "false": returns data only. */
                    "x-request-count"?: string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description First matching record or null */
                200: {
                    headers: {
                        /** @description Echo of the request tracing ID */
                        "x-request-id"?: string;
                        /** @description Number of records in response */
                        "x-response-count"?: string;
                        /** @description Response format indicator */
                        "x-response-format"?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @default 0 */
                            count: number;
                            data: {
                                id: string;
                                createdBy: string | null;
                                modifiedBy: string | null;
                                code: string;
                                group: string;
                                description: string | null;
                            };
                        } | {
                            id: string;
                            createdBy: string | null;
                            modifiedBy: string | null;
                            code: string;
                            group: string;
                            description: string | null;
                        };
                    };
                };
                /** @description Error Response */
                "4XX": {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Error Response */
                "5XX": {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/configurations/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Find single record by ID */
        get: {
            parameters: {
                query?: {
                    /** @description A comprehensive filter object for querying data, including conditions, field selection, relations, pagination, and sorting. */
                    filter?: Record<string, never>;
                };
                header?: {
                    /** @description Optional request ID */
                    "x-request-id"?: string;
                    /** @description Optional request channel */
                    "x-request-channel"?: string;
                    /** @description Optional request device info */
                    "x-device-info"?: string;
                    /** @description Controls response format. When "true" (default): returns {count, data}. When "false": returns data only. */
                    "x-request-count"?: string;
                };
                path: {
                    /** @description The unique id of the resource */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Single record matching ID or null */
                200: {
                    headers: {
                        /** @description Echo of the request tracing ID */
                        "x-request-id"?: string;
                        /** @description Number of records in response */
                        "x-response-count"?: string;
                        /** @description Response format indicator */
                        "x-response-format"?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @default 0 */
                            count: number;
                            data: {
                                id: string;
                                createdBy: string | null;
                                modifiedBy: string | null;
                                code: string;
                                group: string;
                                description: string | null;
                            };
                        } | {
                            id: string;
                            createdBy: string | null;
                            modifiedBy: string | null;
                            code: string;
                            group: string;
                            description: string | null;
                        };
                    };
                };
                /** @description Error Response */
                "4XX": {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Error Response */
                "5XX": {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        /** @description Delete record by ID (irreversible) */
        delete: {
            parameters: {
                query?: never;
                header?: {
                    /** @description Optional request ID */
                    "x-request-id"?: string;
                    /** @description Optional request channel */
                    "x-request-channel"?: string;
                    /** @description Optional request device info */
                    "x-device-info"?: string;
                    /** @description Controls response format. When "true" (default): returns {count, data}. When "false": returns data only. */
                    "x-request-count"?: string;
                };
                path: {
                    /** @description The unique id of the resource */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deleted record data */
                200: {
                    headers: {
                        /** @description Echo of the request tracing ID */
                        "x-request-id"?: string;
                        /** @description Number of records in response */
                        "x-response-count"?: string;
                        /** @description Response format indicator */
                        "x-response-format"?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @default 0 */
                            count: number;
                            data: {
                                id: string;
                                createdBy: string | null;
                                modifiedBy: string | null;
                                code: string;
                                group: string;
                                description: string | null;
                            };
                        } | {
                            id: string;
                            createdBy: string | null;
                            modifiedBy: string | null;
                            code: string;
                            group: string;
                            description: string | null;
                        };
                    };
                };
                /** @description Error Response */
                "4XX": {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Error Response */
                "5XX": {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        /** @description Partial update record by ID */
        patch: {
            parameters: {
                query?: never;
                header?: {
                    /** @description Optional request ID */
                    "x-request-id"?: string;
                    /** @description Optional request channel */
                    "x-request-channel"?: string;
                    /** @description Optional request device info */
                    "x-device-info"?: string;
                    /** @description Controls response format. When "true" (default): returns {count, data}. When "false": returns data only. */
                    "x-request-count"?: string;
                };
                path: {
                    /** @description The unique id of the resource */
                    id: string;
                };
                cookie?: never;
            };
            /** @description Partial data (only changed fields) */
            requestBody?: {
                content: {
                    "application/json": {
                        code?: string;
                        group?: string;
                        description?: string | null;
                    };
                };
            };
            responses: {
                /** @description Updated record with all current fields */
                200: {
                    headers: {
                        /** @description Echo of the request tracing ID */
                        "x-request-id"?: string;
                        /** @description Number of records in response */
                        "x-response-count"?: string;
                        /** @description Response format indicator */
                        "x-response-format"?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @default 0 */
                            count: number;
                            data: {
                                id: string;
                                createdBy: string | null;
                                modifiedBy: string | null;
                                code: string;
                                group: string;
                                description: string | null;
                            };
                        } | {
                            id: string;
                            createdBy: string | null;
                            modifiedBy: string | null;
                            code: string;
                            group: string;
                            description: string | null;
                        };
                    };
                };
                /** @description Error Response */
                "4XX": {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Error Response */
                "5XX": {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Home page */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/html": string;
                    };
                };
                /** @description Error Response */
                "4XX": {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Error Response */
                "5XX": {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/about": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description About page */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/html": string;
                    };
                };
                /** @description Error Response */
                "4XX": {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Error Response */
                "5XX": {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/sign-in": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Sign In */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Sign-in request body */
            requestBody: {
                content: {
                    "application/json": {
                        /** @description Sign-In Identifier */
                        identifier: {
                            scheme: string;
                            value: string;
                        };
                        /** @description Sign-In Credential */
                        credential: {
                            scheme: string;
                            value: string;
                        };
                        /** @description Authenticate Provider */
                        clientId?: string;
                    };
                };
            };
            responses: {
                /** @description Success Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SignInResponse"];
                    };
                };
                /** @description Error Response */
                "4XX": {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Error Response */
                "5XX": {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/sign-up": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Sign Up */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Sign-up request body */
            requestBody: {
                content: {
                    "application/json": {
                        username: string;
                        credential: string;
                    };
                };
            };
            responses: {
                /** @description Success Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SignUpResponse"];
                    };
                };
                /** @description Error Response */
                "4XX": {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Error Response */
                "5XX": {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/change-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Change password */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Change password request body */
            requestBody: {
                content: {
                    "application/json": {
                        scheme: string;
                        oldCredential: string;
                        newCredential: string;
                        userId: string | number;
                    };
                };
            };
            responses: {
                /** @description Success Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ChangePasswordResponse"];
                    };
                };
                /** @description Error Response */
                "4XX": {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Error Response */
                "5XX": {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/token/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Refresh access token */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: unknown;
                        };
                    };
                };
                /** @description Error Response */
                "4XX": {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Error Response */
                "5XX": {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/who-am-i": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    /** @description Whether to attach user information to currentUser */
                    withUserInformation?: "0" | "1" | "true" | "false";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            userId: string | number;
                            roles: {
                                id: string | number;
                                identifier: string;
                                priority: number;
                            }[];
                            clientId?: string;
                            provider?: string;
                            /** Format: email */
                            email?: string;
                            /** @description Attached when withUserInformation is truthy */
                            userInformation?: {
                                [key: string]: unknown;
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get current user information */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: unknown;
                        };
                    };
                };
                /** @description Error Response */
                "4XX": {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Error Response */
                "5XX": {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ping": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description PING | Request body */
            requestBody?: {
                content: {
                    "application/json": {
                        /** @default PING */
                        type?: string;
                        message: string;
                    };
                };
            };
            responses: {
                /** @description HealthCheck PingPong Message */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @default PONG */
                            type: string;
                            /** Format: date-time */
                            date: string;
                            message: string;
                        };
                    };
                };
                /** @description Error Response */
                "4XX": {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Error Response */
                "5XX": {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Health check status */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            status: string;
                            /** Format: date-time */
                            timestamp: string;
                        };
                    };
                };
                /** @description Error Response */
                "4XX": {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Error Response */
                "5XX": {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description Error Schema
         * @example {
         *       "statusCode": 409,
         *       "message": "A category named %{name} already exists.",
         *       "normalized": {
         *         "text": "A category named %{name} already exists.",
         *         "code": "server.commerce.category.create.duplicate_name",
         *         "args": {
         *           "name": "Ticket"
         *         }
         *       },
         *       "extra": {
         *         "categoryId": 42
         *       },
         *       "requestId": "abc-123-def",
         *       "details": {
         *         "url": "http://localhost:3000/categories",
         *         "path": "/categories"
         *       }
         *     }
         */
        ErrorResponse: {
            statusCode?: number;
            message: string;
            normalized?: {
                text: string;
                code: string;
                args: {
                    [key: string]: unknown;
                };
            };
            extra?: {
                [key: string]: unknown;
            };
            requestId?: string;
            details?: {
                [key: string]: unknown;
            };
        };
        SignInResponse: {
            /** @description Send as `Authorization: Bearer <token>` */
            token: string;
        };
        SignUpResponse: {
            id: string;
            username: string;
        };
        ChangePasswordResponse: {
            id: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
