import { Note, notesTable } from '@/models/note.model';
import { PGlite } from '@electric-sql/pglite';
import { PGliteDriver } from '@venizia/ignis-connectors/postgres/pglite';
import { BasePostgresDataSource } from '@venizia/ignis-connectors/postgres';
import { datasource } from '@venizia/ignis-kernel';
import type { ValueOrPromise } from '@venizia/ignis-helpers/common';
import { RelationalMigrationRunner, type IMigration } from '@venizia/ignis-connectors/relational';
import notesMigrationSql from '../../../migration/0000_mushy_chimera.sql?raw';

interface IDataSourceConfigs {
  /**
   * A directory PGlite owns, or `undefined` for an in-memory database that dies with the tab.
   */
  dataDir?: string;
}

/**
 * `opfs-ahp://` is the only OPFS scheme PGlite accepts - there is no bare `opfs://`. The path after
 * it names a directory inside the origin's private file system, not a disk path.
 */
const DEFAULT_DATA_DIR = 'opfs-ahp://ignis-browser-bff';

/** Keyed by `TABLE_NAME`, which is what Drizzle's relational query API resolves against. */
type TNoteDataSourceSchema = { [Note.TABLE_NAME]: typeof notesTable };

/**
 * Generated by `bun run migrate:generate` in `examples/pglite-quickstart` and copied verbatim.
 * Inlined as text by Vite's `?raw` because the file itself never reaches the browser.
 */
const MIGRATIONS: ReadonlyArray<IMigration> = [
  { name: '0000_mushy_chimera', sql: notesMigrationSql },
];

/**
 * The fourth type parameter is the raw client `getClient()`
 * hands back - `pg.Pool` by default, `PGlite` here.
 */
@datasource({ driver: PGliteDriver })
export class PGliteDataSource extends BasePostgresDataSource<
  IDataSourceConfigs,
  TNoteDataSourceSchema,
  {},
  PGlite
> {
  constructor() {
    super({
      name: PGliteDataSource.name,
      config: { dataDir: DEFAULT_DATA_DIR },
      schema: { [Note.TABLE_NAME]: notesTable },
    });
  }

  override async configure(): Promise<void> {
    // No `mkdirSync` above this line, unlike the server example: OPFS has no parent directories to
    // create, and no filesystem module exists to create them with.
    const client = new PGlite(this.settings.dataDir);
    await client.waitReady;
    this.client = client;

    try {
      // The framework's runner, not a local one: it owns the DDL-and-ledger-row-in-one-transaction
      // property, which is what keeps an interrupted first visit from leaving an unrecoverable
      // half-migrated database in OPFS.
      await new RelationalMigrationRunner({
        driver: this.resolveDriver(),
        // Not the runner's default: this example shipped its own ledger under this name, and the
        // database lives in the visitor's OPFS. Renaming it would read as an empty ledger and
        // re-run `CREATE TABLE` against a database that already has the table.
        ledgerTable: 'ignis_browser_migrations',
        scope: PGliteDataSource.name,
      }).run({ migrations: MIGRATIONS });
    } catch (error) {
      // Nothing else holds this instance once configure() unwinds, and OPFS hands out its access
      // handles exclusively - so leaving it open makes every retry die with
      // `NoModificationAllowedError`, recoverable only by clearing site data by hand.
      // A failure to close is logged and swallowed: it must not replace the migration failure that
      // is the real cause.
      await client.close().catch((closeError: unknown) => {
        this.logger.error(
          '[configure] Failed to close PGlite after a failed migration | error: %s',
          closeError,
        );
      });

      throw error;
    }
  }

  /**
   * PGlite has no URL. Only application code calls
   * this, so the data directory is the honest answer.
   */
  override getConnectionString(): ValueOrPromise<string> {
    return this.settings.dataDir ?? ':memory:';
  }
}
