import { Note, notesTable } from '@/models/note.model';
import { createClient, type Client } from '@libsql/client';
import { datasource, ValueOrPromise } from '@venizia/ignis';
import { BaseSqliteDataSource } from '@venizia/ignis/sqlite';
import { LibSqlDriver } from '@venizia/ignis/sqlite/libsql';
import { drizzle } from 'drizzle-orm/libsql';
import { migrate } from 'drizzle-orm/libsql/migrator';
import { mkdirSync } from 'node:fs';
import { dirname } from 'node:path';

interface IDataSourceConfigs {
  /**
   * `file:` for a local database, `:memory:` to die with the
   * process. Remote Turso cannot hold an explicit transaction.
   */
  url: string;
}

/** Runtime state lives under `app_data/`, which is gitignored repository-wide. */
const DEFAULT_URL = 'file:./app_data/database/local.db';

/** Keyed by `TABLE_NAME`, which is what Drizzle's relational query API resolves against. */
type TNoteDataSourceSchema = { [Note.TABLE_NAME]: typeof notesTable };

/** Generated by `bun run migrate:generate` from the model - never hand-edited. */
const MIGRATIONS_FOLDER = './migration';

/** The fourth type parameter is the raw client `getClient()` hands back. */
@datasource({ driver: LibSqlDriver })
export class SqliteDataSource extends BaseSqliteDataSource<
  IDataSourceConfigs,
  TNoteDataSourceSchema,
  {},
  Client
> {
  constructor() {
    super({
      name: SqliteDataSource.name,
      config: { url: process.env.APP_ENV_SQLITE_URL ?? DEFAULT_URL },
      schema: { [Note.TABLE_NAME]: notesTable },
    });
  }

  override async configure(): Promise<void> {
    // libsql opens the file but never creates its parent, so a missing `app_data/database` is a
    // `SQLITE_CANTOPEN` at boot rather than a fresh database.
    const filePath = this.settings.url.replace(/^file:/, '');
    if (filePath !== this.settings.url) {
      mkdirSync(dirname(filePath), { recursive: true });
    }

    const client = createClient({ url: this.settings.url });

    // Applied in-process rather than by the CLI: an embedded database ships with the app, so there
    // is no deploy step between generating a migration and needing it. `migrate()` records what it
    // has run in `__drizzle_migrations`, so every boot after the first is a no-op.
    await migrate(drizzle({ client }), { migrationsFolder: MIGRATIONS_FOLDER });

    this.client = client;
  }

  override getConnectionString(): ValueOrPromise<string> {
    return this.settings.url;
  }
}
